"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "Mentors",
      [
        {
          id: 1,
          name: "Guy Galil",
          company: "ibm",
          email: "example@gmail.com",
          phone: "1234567890",
          address: "Tel Aviv, Israel",
          role: "full stack developer",
          experience: 10,
          gender: "male",
          available: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 2,
          name: "Tomer Bab",
          company: "apple",
          email: "example1@gmail.com",
          phone: "123456789",
          address: "Tel Aviv, Israel",
          role: "full stack developer",
          experience: 20,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 3,
          name: "Gal Cohen",
          company: "intel",
          email: "example5@gmail.com",
          phone: "1234567890",
          address: "Jerusalem, Israel",
          role: "full stack developer",
          experience: 7,
          gender: "female",
          available: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 4,
          name: "Yosi Cohen",
          company: "Google",
          email: "example2@gmail.com",
          phone: "1234567890",
          address: "Ashdod, Israel",
          role: "full stack developer",
          experience: 15,
          gender: "male",
          available: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 5,
          name: "Matan Green",
          company: "Google",
          email: "example6@gmail.com",
          phone: "1234567890",
          address: "Herzliya, Israel",
          role: "full stack developer",
          experience: 3,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 6,
          name: "Noam Shalom",
          company: "Google",
          email: "example6@gmail.com",
          phone: "1234567890",
          address: "Rehovot, Israel",
          role: "full stack developer",
          experience: 3,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 7,
          name: "Shay Natan",
          company: "Google",
          email: "example6@gmail.com",
          phone: "1234567890",
          address: "Afula, Israel",
          role: "full stack developer",
          experience: 3,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 8,
          name: "Gal Sagy",
          company: "Google",
          email: "example6@gmail.com",
          phone: "1234567890",
          address: "Beer-Sheva, Israel",
          role: "full stack developer",
          experience: 3,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 9,
          name: "Neta Ramon",
          company: "Google",
          email: "example6@gmail.com",
          phone: "1234567890",
          address: "Netanya, Israel",
          role: "full stack developer",
          experience: 3,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 10,
          name: "Pini Ramon",
          company: "Google",
          email: "example6@gmail.com",
          phone: "1234567890",
          address: "Bet Shemesh, Israel",
          role: "full stack developer",
          experience: 3,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "יהונתן לוסקי",
          company: "Intel",
          email: "yehonatan.lusky@intel.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "חוקר אבטחת מידע",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "עומר תלמי",
          company: "אורבוטק",
          email: "omertalmi2@gmail.com",
          phone: "",
          address: "נחשונים, Israel",
          role: "sw group manager",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "אלעד הוקסטר",
          company: "sixdof space",
          email: "elad.hechster@gmail.com",
          phone: "",
          address: "Jerusalem, Israel",
          role: "אלגוריתמיקאי",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "אלעד בן אקון",
          company: "Cybereason",
          email: "elad@cybereason.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "ראש צוות",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "אברהם זרוק",
          company: "מערך הסייבר",
          email: "az@cyber.gov.il",
          phone: "",
          address: "Jerusalem, Israel",
          role: "ראש אגף בכיר פיתוח ואינטגרציה",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "משה",
          company: "עצמאי",
          email: "Kaganmoshe90@gmail.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "Software Developer",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Jaffa Sztejnbok",
          company: "IBM",
          email: "jaffas@il.ibm.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "SW Architect, Developer Advocate",
          experience: null,
          gender: "female",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "תומר טלגם",
          company: "מערך הסייבר",
          email: "TomerT@cyber.gov.il",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "יועץ לראש המערך",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "איינשטיין אריאל",
          company: "Verint",
          email: "ariel.eisenstein@verint.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "R&D SW Developer",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "רועי סולדין",
          company: "IBM",
          email: "roy.soldin1@ibm.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "Software Engineer",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "איתי פיינר",
          company: "IBM",
          email: "itay.fainer@ibm.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "Cyber-security & ML Infra development Group",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "זיו סרלין",
          company: "Amazon",
          email: "serziv@gmail.com",
          phone: "",
          address: "גבעתיים, Israel",
          role: "מהנדס פיתוח בכיר",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "אלה לודקין",
          company: "Intel",
          email: "ella.lodkin@intel.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "Security Researcher",
          experience: null,
          gender: "female",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "אבי ויזל",
          company: "IBM",
          email: "Aviv@il.ibm.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role:
            "University Relations Manager -IBM Israel at IBM Development Advocate",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "ניר לייבר",
          company: "Verint",
          email: "",
          phone: "",
          address: "Herzliya, Israel",
          role: "ראש קבוצת מחקר ופיתוח",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "שי סער",
          company: "Verint",
          email: "shai.saar@verint.com",
          phone: "",
          address: "Herzliya, Israel",
          role: "Partner at HR Systems",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "ולדימיר בספלקו",
          company: "Verint",
          email: "vladimir.bespalko@verint.com",
          phone: "",
          address: "חדרה, Israel",
          role: "ראש צוות פיתוח BE",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "מיכל גולד",
          company: "IBM",
          email: "mgold@redhat.com",
          phone: "",
          address: "חדרה, Israel",
          role: "QE",
          experience: null,
          gender: "female",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "בן רזנבי",
          company: "Cybereason",
          email: "ben.raznabi@cybereason.com",
          phone: "",
          address: "גבעתיים, Israel",
          role: "DevOps Team Lead at Cybereason",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "עידו אולבסקי",
          company: "Insight",
          email: "ido@intsights.com",
          phone: "",
          address: "גבעתיים, Israel",
          role: "ראש צוות פיתוח",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Ezra Caltum",
          company: "Intel",
          email: "ezra.caltum@intel.com",
          phone: "",
          address: "רמת גן, Israel",
          role: "Firmware Engineer",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "ליפו הווארסטוק גיא",
          company: "Verint",
          email: "lipo.hawerstock@verint.com",
          phone: "",
          address: "Herzliya, Israel",
          role: "R&D Team Lead",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "אמיר חוזז",
          company: "Insights",
          email: "amir@intsights.com",
          phone: "",
          address: "גני תקווה, Israel",
          role: "VP R&D",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "חגי בן שושן",
          company: "Insights",
          email: "hagay@intsights.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "R&D Group Leader",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "נועה כהן",
          company: "בית הספר לסייבר",
          email: "cohen.machlin.noa@gmail.com",
          phone: "",
          address: "גני תקווה, Israel",
          role: "מפקדת בית הספר לסייבר",
          experience: null,
          gender: "female",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "אורי ליבה בר",
          company: "Cybereason",
          email: "ori.libhaber@cybereason.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "senior Java developer",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "ציפי גיבור",
          company: "כלמוביל",
          email: "tsipi.gibor@gmail.com",
          phone: "",
          address: "אור יהודה, Or Yehuda, Israel",
          role: "full stack developer",
          experience: null,
          gender: "female",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "דוד רוטנברג",
          company: "טלפייר",
          email: "sh13david@gmail.com",
          phone: "",
          address: "נתניה, Israel",
          role: "IOT-סמנכל פיתוח מתמחה בסייבר ו",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "משה שטרנגר",
          company: "Cybereason",
          email: "moshe.strenger@cybereason.com",
          phone: "",
          address: "נתניה, Israel",
          role: "ראש צוות",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "סרגיי",
          company: "אלביט",
          email: "Sergey.Rura@elbitsystems.com",
          phone: "",
          address: "כפר סבא, Israel",
          role: "מנהל תחום פיתוח",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "יאיר מרטוביץ",
          company: "Cybereason",
          email: "yair.martonovich@cybereason.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "sofftware engineer C++",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "יוסי רחמן",
          company: "Cybereason",
          email: "yossi.rachman@cybereason.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "מנהל תחום מחקר",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "נועה קטוביץ",
          company: "Cybereason",
          email: "noa.katsovich@cybereason.com",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "product manager",
          experience: null,
          gender: "female",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "חיים ליטווק",
          company: "מערך הסייבר",
          email: "haiml@cyber.gov.il",
          phone: "",
          address: "חולון, Israel",
          role: "ר' תחום בכיר פרוייקטים ומערכות",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "בלה פיקובסקי",
          company: "checkpoint",
          email: "bella.pikovsky@gmail.com",
          phone: "",
          address: "ראשון לציון, Israel",
          role: "מנהלת פרוייקטיי תוכנה",
          experience: null,
          gender: "female",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "אורן בושמיץ",
          company: "מערך הסייבר",
          email: "orenb@cyber.gov.il",
          phone: "",
          address: "Tel Aviv, Israel",
          role: "CTO",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "בני זלצר",
          company: "Intel",
          email: "benny.zeltser@intel.com",
          phone: "",
          address: "חיפה, Israel",
          role: "Security Researcher",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "בר מולגה",
          company: "Insights",
          email: "bar@intsights.com",
          phone: "",
          address: "ראשון לציון, Israel",
          role: "ראש צוות פיתוח",
          experience: null,
          gender: "male",
          available: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("Mentors", null, {});
  },
};
