"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "Mentors",
      [
        {
          id: 1,
          name: "גבי צדוק",  
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "תפקיד- Director, Blockchain and IoT Platforms, IBM Research",
          company: "חברה- IBM",
          phone: "054-6976377",
          email: "zodik@il.ibm.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 2,
          name: "אילנה קופרמן",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "System Architect",
          company: "Mobileye",
          phone: "0545664901",
          email: "elana.copperman@mobileye.com",
          address: "ירושלים",
          education: "PhD - Hebrew University",
          age: 59,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 35,
        },
        {
          id: 3,
          name: "הדסה ונגרובר",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "מפתחת תוכנה Full Stack Developer",
          company: "Flywire",
          phone: "0-548441860",
          email: "hadasagr@gmail.com",
          address: "בני ברק",
          education:
            "תואר ראשון במדעי המחשב - מכון לוסטיג. הנדסאות תכונה - סמינר הרב וולף - המכללה למינהל ראשל״צ",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 9,
        },
        {
          id: 4,
          name: "מלי רוזנברג",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role:
            "Senior Java\\JEE develper (with Devops experience) | working in mPrest",
          company: "mPrest",
          phone: "050-4130678",
          email: "maliros1234@gmail.com",
          address: "פתח תקוה",
          education:
            "-Practical Engineers - Degree (P.E) Computer Software Engineering\n-Certified middle school teacher in Judaism and computer science\nPetah Tikva Beit Yaakov Seminar",
          age: 26,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 6.7,
        },
        {
          id: 5,
          name: "אלישבע מנדלמן",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: 'ר"צ פיתוח אחראית על מערכות המסחר והסליקה מול הבורסות בעולם.',
          company: "בנק הפועלים",
          phone: "054-9145695",
          email: "elish1001@gmail.com",
          address: "תל אביב",
          education:
            "תואר ראשון במדעי המחשב ממכון לב ותואר שני במתמטיקה פיננסית מבר אילן",
          age: 30,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 10,
        },
        {
          id: 6,
          name: "אפרת הכסטר",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "דתי/ה",
          role: "מנהלת קבוצת מחקר בתמונות רפואיות",
          company: "IBM",
          phone: "0545691128",
          email: "efrathex@il.ibm.com",
          address: "ירושלים",
          education: "תאר ראשון בכלכלה בבר אילן וקורס הסבה במחשבים",
          age: 47,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 24,
        },
        {
          id: 7,
          name: "טליה ברקוביץ",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "אחר",
          role: "מנהלת צוות production PM",
          company: "מובילאיי",
          phone: "0528877155",
          email: "talia.berkowitz@mobileye.com",
          address: "ירושלים",
          education: "תואר ראשון מדעי המחשב ותואר שני מנהל עסקים - HUJI",
          age: 35,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 10,
        },
        {
          id: 8,
          name: "קסם מאיר",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חילוני/ת",
          role: "Algorithm developer\nמחקר ודאטה סיינס\n(פחות קוד רביו וגיט)",
          company: "Cartica AI",
          phone: "0542070367",
          email: "kessemm@gmail.com",
          address: "תל אביב",
          education: "האוניברסיטה העברית, תואר בפיזיקה",
          age: 29,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 3,
        },
        {
          id: 9,
          name: "שושנה (שושי) הלר",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "מפתחת בכירה צוות JAVA",
          company: "בנק הפועלים",
          phone: "0548490775",
          email: "shoshiheller94@gmail.com",
          address: "ירושלים",
          education: 'תעודת הנדסאית מה"ט',
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 6,
        },
        {
          id: 10,
          name: "אפרת (אפי) רותם (רותם צדוק)",
          preference: "דקל/דפנה, (יכולה גם עם ערבי)",
          available: false,
          gender: "אישה",
          religion_level: "דתי/ה",
          role: "מפתחת (מתכנתת)",
          company: "SAP",
          phone: "0525344330",
          email: "efi411@gmail.com",
          address: "",
          education: "תואר ראשון במדעי המחשב - בר אילן",
          age: 30,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 3,
        },
        {
          id: 11,
          name: "ריקי קליין",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "ראש צוות פיתוח",
          company: "ביטוח ישיר",
          phone: "0544908424",
          email: "Riki.klain@gmail.com",
          address: "בני ברק",
          education: "הנדסאית תוכנה מהט",
          age: 33,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 12,
        },
        {
          id: 12,
          name: "חני יהודה",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "מנהלת מוצר",
          company: "Ex Libris",
          phone: "052-7636442",
          email: "chaniyehuda@gmail.com",
          address: "בית שמש",
          education: "",
          age: 38,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 14,
        },
        {
          id: 13,
          name: "קטי רוטמן",
          preference: "דקל אישה",
          available: false,
          gender: "אישה",
          religion_level: "חילוני/ת",
          role: "מפתחת תוכנה",
          company: "SentinelOne",
          phone: "0523908496",
          email: "katy246@gmail.com",
          address: "אריאל",
          education: "תואר ראשון בהנדסת מחשבים בטכניון",
          age: 43,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 16,
        },
        {
          id: 14,
          name: "אלן אמסל",
          preference: "דקל, לערבים דוברי אנגלית בלבד",
          available: false,
          gender: "אישה",
          religion_level: "דתי/ה",
          role: "Privacy and Regulation Officer & DPO",
          company: "Ex Libris",
          phone: "0502026775",
          email: "ellen.amsel@exlibrisgroup.com",
          address: "ירושלים",
          education:"2 graduate degrees: University of Phoenix and Norwich University",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 30,
        },
        {
          id: 15,
          name: "עידו אלעד",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "Director of Product Management",
          company: "40Nuggets",
          phone: "054-4302210",
          email: "ido@autoleadstar.com",
          address: "",
          education: "תואר ראשון בהנדסת מחשבים מהאוניברסיטה העברית",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 7,
        },
        {
          id: 16,
          name: "רון אפלבאום",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "דתי/ה",
          role: "Front End Tech Lead",
          company: "AutoLeadStar",
          phone: "0586256256",
          email: "ron@autoleadstar.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 17,
          name: "לב גליק",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "Software Development Manager",
          company: "Amazon",
          phone: "0טורונטו, קנדה",
          email: "lev.glick@gmail.com",
          address: "טורונטו",
          education:
            "תואר ראשון במדעי המחשה B.Sc- מרכז אקדמי לב (לוסטיג), וגם במהלך לימודים לקראת תואר שני בפסיכולוגיה",
          age: 40,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 15,
        },
        {
          id: 18,
          name: "יואל תהובר",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "Safety Architecture At Product Management",
          company: "Mobileye",
          phone: "0545664131",
          email: "Yoel.Tahover@mobileye.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 19,
          name: "רחל קוזניץ",
          preference: "דפנה, יכולה ל-2",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "Director automation and QA",
          company: "Finastra LTD",
          phone: "0526116524",
          email: "rkuznits@gmail.com",
          address: "פתח תקווה",
          education: 'אקדמאית - תואר ראשון מדמ"ח',
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 9,
        },
        {
          id: 20,
          name: "מירי דונט",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "מנהלת הבדיקות של ממשל זמין , יועצת ומטמיעת אג'ייל",
          company: "ממשל זמין",
          phone: "0534303051",
          email: "mirid@cio.gov.il",
          address: "מודיעין עילית",
          education: "אקדמאית. תואר ראשון גור בב",
          age: 40,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 13,
        },
        {
          id: 21,
          name: "דבורה גודלשמידט",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "Software Architect",
          company: "NICE Actimize",
          phone: "0523692330",
          email: "debyroth340@gmail.com",
          address: "רמת השרון",
          education: 'הנדסאית תוכנה מטעם מה"ט. סטודנטית למדעי המחשב בפתוחה.',
          age: 30,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 10,
        },
        {
          id: 22,
          name: "פרחית לינצר",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חרדי/ת",
          role: "מנהלת מחלקת תפעול אשראי",
          company: "בנק דיסקונט",
          phone: "0526164584",
          email: "pirchit.lintzer@gmail.com",
          address: "בני ברק",
          education: "מכון לב, תואר חלקי במדעי המחשב",
          age: 46,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 22,
        },
        {
          id: 23,
          name: "מיכל רוזנטל",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "חילוני/ת",
          role: "מפתחת אלגוריתמים",
          company: "Waycare",
          phone: "0524564941",
          email: "michrose302@gmail.com",
          address: "",
          education: "פיזיקה באוניברסיטה העברית",
          age: 30,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: 4,
        },
        {
          id: 24,
          name: "אלון שלתיאל",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "אלגוריתמאי",
          company: "Mobileye",
          phone: "0587119417",
          email: "Alon.Shaltiel@mobileye.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 25,
          name: "חמי (נחמה) קרמר",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "",
          role: "מנהלת פרויקטים -מטריקס",
          company: "מטריקס",
          phone: "054-8247002\nאולי 3 בסוף",
          email: "chamikr@gmail.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 26,
          name: "מירי יובל",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "דתי/ה",
          role: "מהנדסת תוכנה בכירה",
          company: "קוואלקום ישראל",
          phone: "0523339961",
          email: "miriyovel4@gmail.com",
          address: "פתח תקווה",
          education: "בוגרת הנדסת חשמל ואלקטרוניקה מהטכניון-BSc",
          age: 23,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 27,
          name: "דסי שוינגר",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "",
          role: "מנהלת טכנולוגית של לקוחות technical success manager",
          company: "cloudinary",
          phone: "054-4724412",
          email: "hadasschwinger@gmail.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 28,
          name: "פנינה קראוס",
          preference: "יכולה דקל, מעדיפה דפנה",
          available: false,
          gender: "אישה",
          religion_level: "",
          role: "VP Software Developer",
          company: "JP Morgan Chase",
          phone: "058-7982406",
          email: "Penina.e.kraus@jpmorgan.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 29,
          name: "נעה כהן",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "",
          role: "מרצה במכללה",
          company: "מכללת עזריאלי להנדסה ירושלים",
          phone: "0542088526",
          email: "cohenoa@gmail.com",
          address: "ירושלים",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 30,
          name: "זיו סרלין",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "מהנדס פיתוח בכיר",
          company: "Amazon",
          phone: "0546898789",
          email: "serziv@gmail.com",
          address: "גבעתיים",
          education: "מגבעתיים עם 20 שנות ניסיון",
          age: 20,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 31,
          name: "אליה פרנקין",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "Algorithm Developer at Mobileye",
          company: "Mobileye",
          phone: "0",
          email: "Elia.Frankin@mobileye.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 32,
          name: "זוהר ג'קסון",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "Team Leader at Mobileye",
          company: "Mobileye",
          phone: "058-728-6231",
          email: "Zohar.Jackson@mobileye.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 33,
          name: "רועי פרנקל לוי",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "Algorithm Engineer at Mobileye",
          company: "Mobileye",
          phone: '0ארה"ב',
          email: "Roi.Frenkel-Levy@mobileye.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 34,
          name: "אלי יפרח",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "cloud Architecture Director",
          company: "Exlibris",
          phone: "0",
          email: "Elie.Ifrah@exlibrisgroup.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 35,
          name: "אסף ויינריב",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "",
          company: "Exlibris",
          phone: "0542390540",
          email: "Assaf.Weinrib@exlibrisgroup.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 36,
          name: "דפנה וולושין",
          preference: "דפנה, יכולה דקל אך מעדיפה אישה",
          available: false,
          gender: "אישה",
          religion_level: "",
          role: "מהנדסת תוכנה- Software Engineer",
          company: "Google",
          phone: "0542490723",
          email: "dafnavolo@gmail.com",
          address: "תל אביב",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 37,
          name: "אסף אמיר",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "VP Research\nפחות קוד רביו וגיט",
          company: "SentinelOne",
          phone: "050-2323459",
          email: "asafa@sentinelone.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 38,
          name: "דניאל יאורי",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "מפתח ביג דאטה",
          company: "SentinelOne",
          phone: "0533403323",
          email: "daniely@sentinelone.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 39,
          name: "חגית מריומה",
          preference: "דפנה",
          available: false,
          gender: "אישה",
          religion_level: "דתי/ה",
          role: "מתכנתת ואינטגרטורית, בעבר הרצתה",
          company: "mobileye",
          phone: "0587705674",
          email: "Hagit.Maryuma@mobileye.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
        {
          id: 40,
          name: "רועי מיכאל",
          preference: "דקל",
          available: false,
          gender: "גבר",
          religion_level: "",
          role: "Senior Software Engineer",
          company: "SentinelOne",
          phone: "0504054104",
          email: "roym@sentinelone.com",
          address: "",
          education: "",
          age: null,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
          experience: null,
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("Mentors", null, {});
  },
};
