version: '3.1'

services:

    mysql:
      image: mysql
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: database_development
        MYSQL_USER: root
      volumes: 
        - mysql-data:/var/lib/mysql
      networks: 
        - crm-network

    api-server:
      depends_on:
        - mysql
      build:
        context: .
        dockerfile: Dockerfile
      image: crmtesting
      ports: 
          - "8080:8080"
      networks: 
        - crm-network
      environment:
        REACT_APP_ONE: REACT_APP_ONE
        REACT_APP_TWO: REACT_APP_TWO
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: database_development
        MYSQL_HOST: mysql

    # migrateAndSeed:
    #     image: crmappcomplete
    #     command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "dbup"]
    #     links:
    #       - mysqlj
    #         - api-server
    #     image: crmappclient
    #     ports: 
    #         - "3000:3000"
    #     stdin_open: true
        # networks: 
        #   - crm-network

networks:
  crm-network:
    driver: bridge
volumes: 
  mysql-data:
    driver: local
