version: "3.1"

services:
  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: crm_database
      MYSQL_USER: root
    # volumes:
    #   - mysql-datav3:/var/lib/mysql
    networks:
      - crm-network

  api-server:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.multistage
    image: crm-multi
    ports:
      - "8081:8081"
    networks:
      - crm-network
    env_file:
      - ./server/src/.env
    command: "./wait-for-it/wait-for-it.sh mysql:3306 -- npm run spinup:staging"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      NODE_ENV: development
      MYSQL_DATABASE: crm_database
      MYSQL_DATABSE_TEST: crm_test
      MYSQL_HOST: mysql
      PORT: 8081

networks:
  crm-network:
    driver: bridge
# volumes:
#   mysql-datav3:
#     driver: local
