GET http://localhost:8080/api/v1/job/all

# response for get all jobs. Same response for get by id and post.
[
  {
    "id": 1,
    "position": "ceo",
    "company": "ibm",
    "description": "hello",
    "contact": "hello",
    "location": "hello",
    "requirements": "hello",
    "additionalDetails": "hello",
    "createdAt": "2020-11-19T11:12:51.000Z",
    "updatedAt": "2020-11-19T11:12:51.000Z",
    "deletedAt": null,
    "Events": [
      {
        "status": "stated application process",
        "createdAt": "2020-11-19T15:08:11.000Z",
        "Student": {
          "id": 2,
          "firstName": "Amir",
          "lastName": "Debbie",
          "idNumber": "219511141",
          "email": "amird812@gmail.com",
          "phone": "054-5610405",
          "age": 22,
          "address": "Moran st, Tel Aviv",
          "maritalStatus": "Single",
          "children": 0,
          "academicBackground": "None",
          "militaryService": "Combat Intelagence",
          "workExperience": "None",
          "languages": "Hebrew, English",
          "citizenship": "Israel",
          "additionalDetails": "this is additionalDetails",
          "classId": 1,
          "createdAt": "2020-11-19T13:38:15.000Z",
          "updatedAt": "2020-11-19T13:54:57.000Z",
          "deletedAt": null
        }
      }
    ]
  }
]
###
GET http://localhost:8080/api/v1/student/all

# response for get all students. same response for get by id and post.
[
  {
    "id": 2,
    "firstName": "Amir",
    "lastName": "Debbie",
    "idNumber": "219511141",
    "email": "amird812@gmail.com",
    "phone": "054-5610405",
    "age": 22,
    "address": "Moran st, Tel Aviv",
    "maritalStatus": "Single",
    "children": 0,
    "academicBackground": "None",
    "militaryService": "Combat Intelagence",
    "workExperience": "None",
    "languages": "Hebrew, English",
    "citizenship": "Israel",
    "additionalDetails": "this is additionalDetails",
    "classId": 1,
    "createdAt": "2020-11-19T13:38:15.000Z",
    "updatedAt": "2020-11-19T13:54:57.000Z",
    "deletedAt": null,
    "Events": [
      {
        "status": "stated application process",
        "createdAt": "2020-11-19T15:08:11.000Z",
        "Job": {
          "id": 1,
          "position": "ceo",
          "company": "ibm",
          "description": "hello",
          "contact": "hello",
          "location": "hello",
          "requirements": "hello",
          "additionalDetails": "hello",
          "createdAt": "2020-11-19T11:12:51.000Z",
          "updatedAt": "2020-11-19T11:12:51.000Z",
          "deletedAt": null
        }
      }
    ]
  }
]
###

GET http://localhost:8080/api/v1/class/all

# response for get all classes. same response for get by id and post.
[
  {
    "id": 1,
    "course": "Cyber4s",
    "name": "Cyber4s",
    "startingDate": "2020-05-31T21:00:00.000Z",
    "endingDate": "2020-12-30T22:00:00.000Z",
    "cycleNumber": 1,
    "zoomLink": "zoom.co.il/789bdjdk",
    "additionalDetails": "DAAAAMmmmnnnnnn",
    "createdAt": "2020-11-19T11:12:51.000Z",
    "updatedAt": "2020-11-19T11:12:51.000Z",
    "deletedAt": null,
    "Students": [
      {
        "id": 2,
        "firstName": "Amir",
        "lastName": "Debbie",
        "idNumber": "219511141",
        "email": "amird812@gmail.com",
        "phone": "054-5610405",
        "age": 22,
        "address": "Moran st, Tel Aviv",
        "maritalStatus": "Single",
        "children": 0,
        "academicBackground": "None",
        "militaryService": "Combat Intelagence",
        "workExperience": "None",
        "languages": "Hebrew, English",
        "citizenship": "Israel",
        "additionalDetails": "this is additionalDetails",
        "classId": 1,
        "createdAt": "2020-11-19T13:38:15.000Z",
        "updatedAt": "2020-11-19T13:54:57.000Z",
        "deletedAt": null
      }
    ]
  },
  {
    "id": 2,
    "course": "Cyber4s",
    "name": "Cyber4s 2",
    "startingDate": "2020-05-31T21:00:00.000Z",
    "endingDate": "2020-12-30T22:00:00.000Z",
    "cycleNumber": 1,
    "zoomLink": "zoom.co.il/789bdjdk",
    "additionalDetails": "DAAAAMmmmnnnnnn",
    "createdAt": "2020-11-19T11:41:55.000Z",
    "updatedAt": "2020-11-19T11:41:55.000Z",
    "deletedAt": null,
    "Students": []
  }
]
###

POST  http://localhost:8080/api/v1/class
{
  "course": "cyber4s",
  "name": "shahar-class",
  "startingDate": "2020-11-19T13:38:15.000Z",
  "endingDate": "2020-11-19T13:38:15.000Z",
  "cycleNumber": 4,
  "zoomLink": "www.shahar.com",
  "additionalDetails": "shahar is the man brah wasuppppp",
}

###