POST http://localhost:8080/api/v1/webhook/team
Content-Type:application/json 

{
    "teamName": "crmTest",
    "leaders": [
        {"userName":"alonbru"}
    ],
    "usersToCreate":[
        {
            "userName":"alon2", 
            "email": "indyalon@gmail.com"
        },
        {
            "userName":"amit2",
            "email": "amit.nir1803@gmail.com" 
        }
    ] 
}

###
GET http://35.239.15.221:8080/api/v1/webhooks/events/all
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IiQyYSQxMCRmS21qcmF1LkpnUldPdHpqTUZQbmN1dzVrd0xBV2JNV2llT25OSWN0WkxxcVFxMjhvdDlVNiIsIm5hbWUiOiJjcm0iLCJpZCI6NDgsImlhdCI6MTYwOTI1MDI5M30.0Zc0tcWWxfBXeuFRyu8QqRgcmd-CaB8cYqEassKjclU

###
{
  "eventName":"submittedChallenge",
  "userId":1,
  "userName":"suvelocity",
  "challengeName":"React Recoil",
  "submissionState":"SUCCESS",
  "team":"teamC"
}
{
  "userName": "alon2",
  "password": "ornmf5Bl"
},
{
  "userName": "amit2",
  "password": "yfth06T3"
}

###
POST http://localhost:8080/api/v1/event/challengeMe
Content-Type: application/json

{
  "eventName": "Submitted Challenge",
  "userName": "nitzan",
  "userMail":"student@student.com",
  "challengeId":5,
  "challengeName": "fuck a duck",
  "submissionState": "FAIL",
  "team": "string"
}